// funny_react/src/routes/account/join.js
import React, { Component } from 'react';

import {joinUser} from '../../connect/getUser'

class join extends Component {
    constructor(props){
        super(props);
        this.state = {
    
        }
    }

    render(){
        return(
            <form onSubmit={this.evtHandler}>
            <div>
                <ul>
                    <li>이름 : <input type="text" class="userName" name="userName"/></li>
                </ul>
                <ul>
                    <li>아이디 : <input type="text" class="userId" name = "userId"/></li>
                </ul>
                <ul>
                    <li>비밀번호 : <input type="password" class="userPasswd" name="userPasswd"/></li>
                </ul>
                <ul>
                    <li>주소 : <input type="text" class="userAddress" name="userAddress" /></li>
                </ul>
                <ul>
                    <li>생년월일 : <input type="text" class="userBirthday" name="userBirthday"/></li>
                </ul>
                <ul>
                    <li>성별 : 
                        <input type="radio" class="userSex" name="userSex" value="m" />남
                        <input type="radio" class="userSex" name="userSex" value="f" />여
                    </li>
                </ul>
                <button type="submit" >가입하기 </button>
            </div>
            </form>
        )
    }

    join = async() => {
        await joinUser().then((res) => {

        })
    }

    evtHandler = async(e) => {
        e.preventDefault();
        console.info('핸들러 동작', e.target.userName.value);
        console.info('핸들러 동작', e.target.userId.value);
        console.info('핸들러 동작', e.target.userPasswd.value);
        console.info('핸들러 동작', e.target.userAddress.value);
        console.info('핸들러 동작', e.target.userBirthday.value);
        console.info('핸들러 동작', e.target.userSex.value);
        let userData = {
            "user_id":e.target.userId.value, 
	        "user_passwd":e.target.userPasswd.value,
	        "user_name":e.target.userName.value,
	        "user_address":e.target.userAddress.value,
	        "user_birthday":e.target.userBirthday.value,
	        "user_sex":e.target.userSex.value
        }
        
        await joinUser(userData).then((res) => {
            console.info('결과 : ', res);
            if(res.status === 200){
                alert('회원가입에 성공하였습니다.');
                this.props.history.replace('/main')
            }

        })
    }

}
export default join

// funny_vue/src/components/account/join.vue
<template>
    <div>
        <ul>
            <div>
                <span>아이디 : </span>
                <input type="text" v-model="userId"/>
            </div>
            <div>
                <span>비밀번호 : </span>
                <input type="text" v-model="userPasswd"/>
            </div>
            <div>
                <span>이름 : </span>
                <input type="text" v-model="userName"/>
            </div>
            <div>
                <span>주소 : </span>
                <input type="text" v-model="userAddress"/>
            </div>
            <div>
                <li>성별 : 
                    <input type="radio" class="userSex" name="userSex" value="m" v-model="userSex" />남
                    <input type="radio" class="userSex" name="userSex" value="f" v-model="userSex" />여
                </li>
            </div>
            <div>
                <span>생년월일 : </span>
                <input type="text" v-model="userBirthday"/>
            </div>
            <button @click="joinUser">회원가입</button>
        </ul>
    </div>
</template>
<script>
export default {
  data(){
      return {
          userId:'',
          userPasswd:'',
          userName:'',
          userAddress:'',
          userSex:'',
          userBirthday:''
      }
  },
  methods:{
        joinUser(){
            let user_info = {
                'user_id': this.userId,
                'user_passwd': this.userPasswd,
                'user_name': this.userName,
                'user_address': this.userAddress,
                'user_birthday':this.userBirthday,
                'user_sex': this.userSex
            }

            this.axios.post('http://ec2-54-180-31-0.ap-northeast-2.compute.amazonaws.com:3005/study/addUser', user_info
            )
            .then((res) => {
              if(res.status === 200 ){
                  alert('회원가입에 성공하였습니다.')
                  this.$router.push('/login');
              }
            })
        }
  }
}
</script>
